services:
  elixir_validator_test:
    container_name: ${CONTAINER_TEST_NAME}
    image: elixirprotocol/validator:testnet
    platform: linux/amd64
    # environment:
    #   - "LOGGING_LEVEL=debug"
    labels:
      - "alias=${LABEL_TEST_ALIAS}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    ports:
      - "17690:17690"
    env_file:
      - ./elixir/test.env
    networks:
      - monitoring


networks:
  monitoring:
    external: true
